config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users, except: [:index, :show]
  resources :number_collectible_attributes
  resources :collectible_attribute_lists
  resources :string_collectible_attributes
  resources :hours
  resources :passport_titles
  resources :reward_title_positions
  resources :reward_titles
  resources :milestone_values
  resources :milestones
  get 'welcome/index'
  resources :island_collections, path: 'collections' do
    get "/sort_by/*sort_by/order/*order/filter/*filter/:id", to: "island_collections#show", as: :sort_and_filter
    get "/sort_by/*sort_by/order/*order/:id", to: "island_collections#show", as: :sort
    get "/set_modal/:id", to: "island_collections#set_modal", as: :set_modal
  end
  get '/collections/fish', as: :fish
  get '/collections/bugs', as: :bugs
  get '/collections/fossils', as: :fossils
  resources :villager_catchphrases
  resources :catchphrases
  resources :birthdays
  resources :villager_genders
  resources :shadow_sizes
  resources :fish_sizes
  resources :timespans
  resources :bug_spots
  resources :fishing_spots
  resources :bug_locations
  resources :locations
  resources :fishing_locations
  resources :time_of_years
  resources :months
  resources :bell_values
  resources :time_of_days
  resources :collectible_attributes
  resources :collectibles do
    patch "/toggle", :to => "collectibles#toggle", :as => "toggle"
  end
  root 'welcome#index'

  get 'auth/auth0/callback' => 'auth0#callback'
  get 'auth/failure' => 'auth0#failure'

  get '/logout' => 'logout#logout'

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/island_collection.rb
class IslandCollection < ApplicationRecord
    extend FriendlyId

    has_and_belongs_to_many :users

    has_many :collectibles

    accepts_nested_attributes_for :collectibles

    friendly_id :title, use: :slugged
end

app/controllers/island_collections_controller.rb
class IslandCollectionsController < ApplicationController
  include Secured

  before_action :set_island_collection, only: [:show, :edit, :update, :destroy]
  before_action :set_user


  # GET /island_collections
  # GET /island_collections.json
  def index
    @island_collections = @user.island_collections
  end

  # GET /island_collections/1
  # GET /island_collections/1.json
  def show
        
    @island_collection = IslandCollection.includes(:collectibles).friendly.find(params[:id])
    
    @collectibles = @island_collection.collectibles.includes(:collectible_attributes)

    if params[:filter]
      
      times_to_check = params[:filter].scan(Regexp.union(TimeOfDay.filters[:active].values))
      months_to_check = params[:filter].scan(Regexp.union(DateTime::MONTHNAMES[1..12].map(&:downcase)))

      if params[:filter].include?('current_month') || months_to_check.size > 0
        @collectibles = @collectibles.select{ |collectible| 
          found = false

          if params[:filter].include?('current_month')
            found = collectible.active_in(month: DateTime::MONTHNAMES[DateTime.current.month])
          end

          months_to_check.each do |month_name|
            unless found
              if collectible.active_in(month: month_name.capitalize)
                found = true
              end
            end
          end

          found
        }
      end
      

      if params[:filter].include?('current_time') || times_to_check.size > 0
        @collectibles = @collectibles.select{ |collectible| 
          found = false

          if params[:filter].include?('current_time') 
            found = collectible.active_at_time(time: Time.current)
          end

          times_to_check.each do |time|
            unless found
              if collectible.active_at_time(time: Time.now.change(hour: DateTime.strptime(time, '%H%P').hour))
                found = true
              end
            end
          end

          found
        }
      end

      if params[:filter] =~ /(?:^|\W)not_complete(?:$|\W)/ && params[:filter] !=~ /(?:^|\W)complete(?:$|\W)/
        @collectibles = @collectibles.select { |collectible|
          !@user.my_collected_collectibles.find_by(collectible_id: collectible.id).completions['first'] == 'true'
        }
      end

      if params[:filter] =~ /(?:^|\W)complete(?:$|\W)/ && params[:filter] !=~ /(?:^|\W)not_complete(?:$|\W)/
        @collectibles = @collectibles.select { |collectible|
        @user.my_collected_collectibles.find_by(collectible_id: collectible.id).completions['first'] == 'true'
        }
      end
    end

    @collectibles = @collectibles.sort_by{|obj| obj.position}
    if params[:sort_by]
      if params[:sort_by] == "Name"
        @collectibles = @collectibles.sort_by{ |collectible| collectible.name }
      elsif params[:sort_by] == "Collected"
        @collectibles = @collectibles.sort_by{ |collectible| @user.my_collected_collectibles.find_by(collectible_id: collectible.id).completions['first'] == 'true' ? 0 : 1 }
      else
        @collectibles = @collectibles.sort_by{|collectible| 
          collectible.collectible_attributes.find_by(label:  params[:sort_by])
         }
      end
      if params[:order] =='desc'
        @collectibles.reverse!  
      end
    end
    

    
  end

  # GET /island_collections/new
  def new
    @island_collection = IslandCollection.new
  end

  # GET /island_collections/1/edit
  def edit
    @island_collection = IslandCollection.friendly.find(params[:id])

    @collectibles = @island_collection.collectibles.includes(:collectible_attributes)

  end

  # POST /island_collections
  # POST /island_collections.json
  def create
    @island_collection = IslandCollection.new(island_collection_params)

    respond_to do |format|
      if @island_collection.save
        format.html { redirect_to @island_collection, notice: 'Island collection was successfully created.' }
        format.json { render :show, status: :created, location: @island_collection }
      else
        format.html { render :new }
        format.json { render json: @island_collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /island_collections/1
  # PATCH/PUT /island_collections/1.json
  def update
    respond_to do |format|
      if @island_collection.update(island_collection_params)
        format.html { redirect_to @island_collection, notice: 'Island collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @island_collection }
      else
        format.html { render :edit }
        format.json { render json: @island_collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /island_collections/1
  # DELETE /island_collections/1.json
  def destroy
    @island_collection.destroy
    respond_to do |format|
      format.html { redirect_to island_collections_url, notice: 'Island collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /island_collections/set_modal/1
  def set_modal
    @collectible = Collectible.find(params[:id])
    @user = User.find(params[:user])
    respond_to do |format|
        format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_island_collection
      @island_collection = IslandCollection.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def island_collection_params
      params.require(:island_collection).permit(:title, :thumbnail, :collectibles_attributes => [:island_collection_id, :name, :thumbnail, :complete, :id])
    end

    def set_user
      @user = User.find_by(auth0_id: session[:userinfo]['uid'])

      if !@user
        redirect_to new_user_path
      end
    end
end

app/helpers/island_collections_helper.rb
module IslandCollectionsHelper
end

app/views/island_collections/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @user.username %>'s Collections</h1>

<section class="island-collections">
	<% @island_collections.each do |island_collection| %>
		<div class="island-collection-item">
			<% unless island_collection.thumbnail == nil%>
				<%= image_tag island_collection.thumbnail, height: '100', width: '100' %>
			<% end %>
			<p><%= island_collection.title %></p>
			<%= link_to 'Show', island_collection, class: 'btn' %>
			<% unless island_collection.default %>
				<%= link_to 'Edit', edit_island_collection_path(island_collection), class: 'btn' %>
				<%= link_to 'Remove', island_collection, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn' %>
			<% end %>
		</div>
	<% end %>
</section>

app/views/island_collections/set_modal.js.erb
$('#modal_contents').replaceWith("<%= escape_javascript render(:partial => 'collectibles/show', :locals => {  collectible: @collectible, user: @user }) %>");
$('.modal-close').on('click', function(e) {
	$('.modal').removeClass("visible-modal");
});
$('#modal-toggle').click(function(){
	checkboxToggle();
});
$('#modal-checkbox').on('change', function(ev){

	var checkbox = $('#' +  $('#modal-checkbox').attr('data_value') + '-complete');

	if (checkbox[0].checked === false) {
		checkbox[0].checked = true;
	}
	else if (checkbox[0].checked == true) {
		checkbox[0].checked = false;
	}

	document.getElementById("count-checked-checkboxes").innerHTML = countCheckedCheckbox();
	
});

app/views/island_collections/show.html.erb
<p id="notice"><%= notice %></p>

<section class="heading">
	<div class="title">
		<h1><%= @island_collection.title %></h1>
    	<p class="collection-count"><span id="count-checked-checkboxes">0</span> / <span id="count-checkboxes">0</span> collected</p>
	</div>
	<div class="sort">
		<% select_options = ["Default", "Name", "Collected"] %>
		<% @island_collection.collectibles.first.collectible_attributes.each do |collectible_attribute| %>
			<% if collectible_attribute.collectible_attribute_value.class < SortableAttribute %>
				<% select_options.push collectible_attribute.label %>
			<% end %>
		<% end %>
		<div class="sort_by">
			<%= select_tag "sort_by", options_for_select(select_options) %>
		</div>
		<div class="order">
			<%= select_tag "order", options_for_select([['A-Z (0-9)', 'asc'], ['Z-A (9-0)', 'desc']]) %>
		</div>
		<br />
		<% @island_collection.collectibles.first.collectible_attributes.each do |collectible_attribute| %>
			<% if collectible_attribute.is_filterable %>
				<% collectible_attribute.collectible_attribute_value.filters.each do |filter|%>
					<% if filter[1].class == Hash %>
						<div class="filter-multi-select" >
							<%= label_tag filter[0] %>
							<%= select_tag filter[0], options_for_select(filter[1].invert), multiple: true, html_options: { multiple: true } %>
						</div>
						<br class="responsive-break">
					<% else %>
						<div class="filter-checkbox">
							<%= check_box_tag filter[0], filter[0]%>
							<%= label_tag filter[1], filter[1],  for: filter[0] %>
						</div>
					<% end %>
				<% end %>
			<% end %>
		<% end %>
		<br />
		<%= link_to 'Sort', island_collection_sort_and_filter_path( sort_by: select_options.first, order: 'asc', filter: 'none' , island_collection_id: @island_collection.id), html_options = { id: 'sort_link' } %>
	</div>
</section>

<section id="collection" class="collection-items">
	<% @collectibles.each do |collectible| %>
		<div>
			<div class="collectible">
				<%= link_to collectible_toggle_path(collectible_id: collectible.id, user_id: @user.id), :data => {:remote => true, :method => :patch} do %>
					<% unless collectible.thumbnail == nil%>
						<%= image_tag collectible.thumbnail, height: '100', width: '100' %>
					<% end %>
				<% end %>
				
				<% if collectible.users.include?(@user)%>
					
					<% completions = @user.my_collected_collectibles.find_by(collectible:collectible).completions %>
					<% if completions %>
						<% completions.each do |completion| %>
							
							<%= check_box_tag "Complete", 
								completion[1], 
								completion[1] == 'true',
								id: collectible.id.to_s + "-complete",
								:data => {:remote => true, :url => url_for(collectible_toggle_path(collectible_id: collectible.id, user_id: @user.id)), :method => :patch } %>
						<% end %>
					<% end %>
				<% end %>

			</div>
			<%= link_to collectible.name, island_collection_set_modal_path(island_collection_id: @island_collection.id, id: collectible.id, user: @user), html_options = { remote: true, class: "modal-btn", id: "btn-" + collectible.id.to_s } %>
		</div>
	<% end %>
</section>

<section class="modals">
	<div class="modal" id="modal">
		<%= puts @user.id%>
		<%= render partial: "collectibles/show", locals: { collectible: @island_collection.collectibles.first, user: @user } %>
	</div>
</section>